Add spotnet network client chart
spotinst/charts pull request #26
Opened 2022-08-24 13:47 UTC by avitalwerz

2022-08-25 08:03 UTC, oded7hoffman requested changes

2022-08-25 08:03 UTC, oded7hoffman commented on charts/ocean-network-client/values.yaml
> +  repository: public.ecr.aws/spotinst-dev/spot-network-client
Is this the right repo, shouldn't it be from Prod?

2022-08-25 12:38 UTC, yinnonbar commented on charts/ocean-network-client/Chart.yaml
> +appVersion: "1.0.0-4-1b8cbd7"
@avitalwerz this the the stable version?

2022-08-25 12:55 UTC, yinnonbar approved these changes

2022-08-28 15:09 UTC, oded7hoffman approved these changes

2022-08-29 07:29 UTC, merged